
import { SkillCategory, Project, ExperienceItem, Certification, Testimonial } from './types';

export const NAV_LINKS = [
  { name: 'Home', href: '#home' },
  { name: 'About', href: '#about' },
  { name: 'Skills', href: '#skills' },
  { name: 'Projects', href: '#projects' },
  { name: 'Experience', href: '#experience' },
  { name: 'Certifications', href: '#certifications' },
  { name: 'Contact', href: '#contact' },
];

export const HERO_STATS = [
  { label: 'Years Experience', value: '3+' },
  { label: 'Completed Projects', value: '20+' },
  { label: 'Git Contributions', value: '1,800+' },
  { label: 'Client Satisfaction', value: '100%' },
];

export const SKILLS_DATA: SkillCategory[] = [
  {
    title: 'Frontend Architecture',
    iconName: 'Layout',
    description: 'Engineering responsive, pixel-perfect, accessible user interfaces with cutting-edge tooling.',
    skills: [
      { name: 'React 19 & Next.js', level: 95, category: 'Frontend', experienceYears: '3 yrs', note: 'Hooks, Suspense, Server Components, State Architecture' },
      { name: 'TypeScript', level: 90, category: 'Frontend', experienceYears: '2.5 yrs', note: 'Strict typing, Generics, Utility types, Modular design' },
      { name: 'JavaScript (ESNext)', level: 95, category: 'Frontend', experienceYears: '3.5 yrs', note: 'Async/Await, Event Loop, Closures, DOM optimization' },
      { name: 'Tailwind CSS & CSS3', level: 98, category: 'Frontend', experienceYears: '3 yrs', note: 'Responsive design, custom tokens, CSS animations' },
      { name: 'HTML5 & Accessibility', level: 98, category: 'Frontend', experienceYears: '4 yrs', note: 'Semantic HTML, WCAG AA compliance, SEO optimization' },
      { name: 'State Management', level: 88, category: 'Frontend', experienceYears: '2.5 yrs', note: 'Zustand, Redux Toolkit, React Context, TanStack Query' },
    ],
  },
  {
    title: 'Backend & Databases',
    iconName: 'Server',
    description: 'Designing scalable microservices, resilient RESTful APIs, and secure database schemas.',
    skills: [
      { name: 'Node.js & Runtime', level: 85, category: 'Backend', experienceYears: '2.5 yrs', note: 'Event-driven architecture, streams, buffer management' },
      { name: 'Express.js', level: 88, category: 'Backend', experienceYears: '2.5 yrs', note: 'Middleware pipelines, routing, JWT auth, rate limiting' },
      { name: 'MongoDB & Mongoose', level: 82, category: 'Backend', experienceYears: '2 yrs', note: 'Aggregation pipelines, indexing, schema validations' },
      { name: 'PostgreSQL & SQL', level: 78, category: 'Backend', experienceYears: '1.5 yrs', note: 'Relational queries, schema migrations, joins' },
      { name: 'REST & GraphQL APIs', level: 86, category: 'Backend', experienceYears: '2 yrs', note: 'API contract design, OpenAPI/Swagger docs' },
      { name: 'Firebase & Cloud Auth', level: 85, category: 'Backend', experienceYears: '2 yrs', note: 'Firestore, Authentication, Cloud Functions, Rules' },
    ],
  },
  {
    title: 'DevOps, Tools & UX',
    iconName: 'Cpu',
    description: 'Streamlining CI/CD workflows, developer experience, and design-to-code pipelines.',
    skills: [
      { name: 'Git & GitHub Workflows', level: 92, category: 'DevOps', experienceYears: '3.5 yrs', note: 'Branching strategies, PR reviews, CI actions' },
      { name: 'Vite & Build Tooling', level: 90, category: 'DevOps', experienceYears: '2.5 yrs', note: 'Bundling, code splitting, HMR, env configs' },
      { name: 'Docker & Containerization', level: 75, category: 'DevOps', experienceYears: '1.5 yrs', note: 'Multi-stage Dockerfiles, compose environments' },
      { name: 'Figma to Code & UI/UX', level: 88, category: 'Design', experienceYears: '3 yrs', note: 'Design systems, auto-layout, interactive prototypes' },
      { name: 'Testing (Jest/Playwright)', level: 80, category: 'DevOps', experienceYears: '2 yrs', note: 'Unit testing, component tests, E2E test suites' },
      { name: 'Performance & Web Vitals', level: 89, category: 'DevOps', experienceYears: '2.5 yrs', note: 'Lighthouse 95+, bundle analysis, asset caching' },
    ],
  },
];

export const PROJECTS_DATA: Project[] = [
  {
    id: 1,
    title: 'DevPulse Cloud Platform',
    tagline: 'Enterprise Real-Time Developer Analytics & Health Monitor',
    description: 'Full-stack cloud engineering dashboard providing instant developer telemetry, repository health metrics, and automated deployment logs.',
    fullOverview: 'DevPulse aggregates metrics from CI/CD pipelines, git repositories, and microservices into a unified, high-contrast dashboard with live charts, alert thresholds, and automated Slack notifications.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
    tags: ['React 19', 'TypeScript', 'Node.js', 'Tailwind CSS', 'Recharts', 'WebSockets'],
    liveUrl: 'https://devpulse-demo.app',
    codeUrl: 'https://github.com/siab-khan/devpulse-platform',
    category: 'Full Stack',
    featured: true,
    metrics: 'Processed 50K+ live telemetry events with <20ms latency',
    highlights: [
      'Engineered interactive real-time visual charts using customized SVG and D3 calculations',
      'Implemented JWT session management with refresh token rotation and role-based ACL',
      'Reduced initial dashboard bundle footprint by 44% with dynamic lazy routes',
    ],
    architecture: ['Client: React + Vite + Tailwind', 'Server: Node.js + Express', 'Database: MongoDB + Redis Cache', 'Real-time: WebSocket protocol'],
    initialStars: 42,
  },
  {
    id: 2,
    title: 'Nexus E-Commerce Engine',
    tagline: 'Ultra-Fast Headless Storefront with Frictionless Checkout',
    description: 'High-performance modern commerce portal featuring sub-second catalog search, persistent wishlist, cart state, and smooth checkout flow.',
    fullOverview: 'Built to demonstrate lightning-fast e-commerce UX, featuring optimistic UI updates for cart modifications, faceted category filters, multi-currency support, and payment flow simulation.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
    tags: ['React', 'TypeScript', 'Express.js', 'MongoDB', 'Stripe Flow', 'Tailwind CSS'],
    liveUrl: 'https://nexus-storefront.app',
    codeUrl: 'https://github.com/siab-khan/nexus-store',
    category: 'Full Stack',
    featured: true,
    metrics: '99+ Lighthouse performance & 0.3s First Contentful Paint',
    highlights: [
      'Instant client-side fuzzy search across 5,000+ inventory catalog items',
      'Optimistic cart mutation synchronization with local storage and remote database',
      'Dark/Light theme design system built with responsive CSS variables',
    ],
    architecture: ['Frontend: React 19 + TypeScript', 'Styling: Tailwind CSS Utility Engine', 'Backend: Express REST API', 'Storage: MongoDB Atlas'],
    initialStars: 38,
  },
  {
    id: 3,
    title: 'Prism UI Design System',
    tagline: 'Accessible Figma-to-Code Component Toolkit',
    description: 'Comprehensive design system and reusable component library crafted with strict WCAG AA compliance, dark mode tokens, and fluid interactions.',
    fullOverview: 'A centralized component ecosystem crafted in Figma and implemented in React with TypeScript. Includes 45+ production-ready components, customizable token themes, and interactive documentation.',
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop',
    tags: ['Figma', 'UI/UX', 'React', 'TypeScript', 'Design Systems', 'Storybook'],
    liveUrl: 'https://prism-tokens.dev',
    codeUrl: 'https://github.com/siab-khan/prism-ui-system',
    category: 'UI Design',
    featured: false,
    metrics: 'Adopted across 6 commercial client deliverables',
    highlights: [
      'Constructed complete token hierarchy (colors, typography, radii, spacing, elevations)',
      '100% keyboard navigable with visible focus rings and ARIA live regions',
      'Interactive playground with live copy-paste code snippets',
    ],
    architecture: ['Design: Figma Variants & Auto-Layout', 'Library: TypeScript + Headless UI + Tailwind', 'Docs: Interactive Sandbox'],
    initialStars: 29,
  },
  {
    id: 4,
    title: 'TaskFlow Kanban Studio',
    tagline: 'Intuitive Agile Workflow & Sprint Board',
    description: 'Kanban board application empowering teams with drag-and-drop card movements, subtask checklists, tag filtering, and priority analytics.',
    fullOverview: 'TaskFlow streamlines team productivity with smooth card interactions, markdown-enabled card descriptions, time tracking estimations, and visual sprint velocity indicators.',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?q=80&w=1200&auto=format&fit=crop',
    tags: ['React', 'TypeScript', 'Drag & Drop', 'Firebase', 'Tailwind CSS'],
    liveUrl: 'https://taskflow-studio.app',
    codeUrl: 'https://github.com/siab-khan/taskflow-kanban',
    category: 'Frontend',
    featured: false,
    metrics: 'Zero lag 60 FPS drag-and-drop operations',
    highlights: [
      'Custom drag-and-drop physics with reordering across multiple columns',
      'Instant offline persistence with automatic online sync resolution',
      'Rich task filtering by priority, assigned tags, and due dates',
    ],
    architecture: ['Client: React Hook state machine', 'Sync: Firebase Firestore Real-time Listeners', 'Security: Granular column permissions'],
    initialStars: 34,
  },
  {
    id: 5,
    title: 'CyberTerminal Web CLI',
    tagline: 'Interactive Developer Terminal & Virtual Shell',
    description: 'Lightweight virtual shell and command emulator with filesystem navigation, custom commands, syntax highlighting, and bash shortcuts.',
    fullOverview: 'An in-browser command line interface designed for developer portfolios and sandbox environments. Supports standard shell commands like ls, cd, cat, grep, as well as custom script triggers.',
    image: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?q=80&w=1200&auto=format&fit=crop',
    tags: ['TypeScript', 'React', 'Shell Emulation', 'CLI', 'Open Source'],
    liveUrl: 'https://cyberterminal-shell.dev',
    codeUrl: 'https://github.com/siab-khan/cyber-terminal-web',
    category: 'Open Source',
    featured: false,
    metrics: '1,200+ NPM weekly downloads',
    highlights: [
      'Emulated virtual in-memory UNIX filesystem with directory traversal',
      'Command history recall with Up/Down arrow navigation and Tab auto-complete',
      'Customizable color themes (Cyberpunk, Matrix Green, Dracula, Monokai)',
    ],
    architecture: ['Core: Pure TypeScript AST token parser', 'Output: Virtual buffer renderer', 'Storage: Local Session State'],
    initialStars: 56,
  },
  {
    id: 6,
    title: 'AI Promptcraft Copilot',
    tagline: 'Context-Aware AI Assistant & Workspace',
    description: 'Modern conversational workspace featuring streaming token responses, code block syntax highlighting, and reusable prompt collections.',
    fullOverview: 'A developer-centric AI productivity assistant with template library, token counters, split-screen code review, and instant export to markdown or gist.',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
    tags: ['React 19', 'TypeScript', 'Streaming UI', 'Tailwind CSS'],
    liveUrl: 'https://promptcraft-ai.app',
    codeUrl: 'https://github.com/siab-khan/promptcraft-workspace',
    category: 'Frontend',
    featured: true,
    metrics: '4.9/5 Average Developer User Score',
    highlights: [
      'Streaming token response animation with zero layout shifts',
      'One-click code snippet copying with visual confirmation feedback',
      'Offline prompt repository stored locally in browser IndexedDB',
    ],
    architecture: ['Interface: React 19 Client Components', 'Markdown: Custom Parser with code highlighting', 'Theme: Cyber-slate neon design'],
    initialStars: 47,
  },
];

export const EXPERIENCE_DATA: ExperienceItem[] = [
  {
    company: 'InnovateTech Solutions',
    role: 'Senior Full Stack Developer',
    period: '2023 - Present',
    location: 'Remote / Hybrid',
    type: 'Full-time',
    responsibilities: [
      'Lead frontend and API architecture for enterprise web applications utilizing React, TypeScript, and Node.js.',
      'Designed and executed modular design systems that slashed feature delivery time across squads by 35%.',
      'Collaborate directly with cross-functional stakeholders, product managers, and UI/UX designers to translate requirements into scalable code.',
      'Mentor 4 junior and mid-level developers through rigorous code reviews, pair programming, and engineering workshops.',
    ],
    achievements: [
      'Architected high-throughput data processing pipeline cutting page load latency by 42%.',
      'Introduced automated end-to-end testing, reducing regression bug rate by 60%.',
    ],
    technologies: ['React 19', 'TypeScript', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS', 'Docker', 'Git'],
  },
  {
    company: 'Apex Digital Studio',
    role: 'Full Stack Web Developer',
    period: '2022 - 2023',
    location: 'Islamabad / Hybrid',
    type: 'Full-time',
    responsibilities: [
      'Constructed customer-facing portals, responsive landing experiences, and e-commerce platforms for 12+ international clients.',
      'Integrated third-party APIs including Stripe payments, OAuth providers, Mailgun, and Google Maps.',
      'Refactored legacy single-page apps to modern React functional patterns, improving SEO and Core Web Vitals score to 96+.',
    ],
    achievements: [
      'Delivered client e-commerce platform that generated $150K+ in transaction volume in its first quarter.',
      'Recognized with "Quarterly Developer of Excellence" award for timely sprint executions.',
    ],
    technologies: ['React', 'JavaScript', 'Tailwind CSS', 'Node.js', 'PostgreSQL', 'Figma', 'REST APIs'],
  },
  {
    company: 'Freelance & Open Source',
    role: 'Frontend & UI Engineer',
    period: '2021 - 2022',
    location: 'Remote',
    type: 'Contract',
    responsibilities: [
      'Delivered bespoke web solutions, custom dashboards, and interactive landing pages for startups and indie creators.',
      'Created reusable open-source components and published technical walkthroughs on web performance and clean React patterns.',
      'Managed end-to-end lifecycle from design concept wireframes in Figma to production deployment on Vercel and Cloud Run.',
    ],
    achievements: [
      'Maintained 100% 5-star rating across 15+ independent contract deliverables.',
    ],
    technologies: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Git', 'Figma', 'Responsive Design'],
  },
];

export const CERTIFICATIONS_DATA: Certification[] = [
  {
    id: 1,
    title: 'Meta Full-Stack Software Engineer Specialization',
    issuer: 'Meta / Coursera',
    date: 'Jan 2024',
    credentialId: 'META-FS-849204',
    verifyUrl: 'https://coursera.org/verify/meta-fullstack',
    skillsCovered: ['React', 'Node.js', 'APIs', 'Database Architecture', 'CI/CD Pipelines'],
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 2,
    title: 'React - The Complete Developer Guide 2024',
    issuer: 'Udemy Academic',
    date: 'Nov 2023',
    credentialId: 'UDEMY-UC-9382104',
    verifyUrl: 'https://udemy.com/certificate/UC-react-pro',
    skillsCovered: ['React 18/19', 'Redux Toolkit', 'Custom Hooks', 'Performance Optimization'],
    image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 3,
    title: 'Node.js, Express & MongoDB Masterclass',
    issuer: 'Udemy Academic',
    date: 'Aug 2023',
    credentialId: 'UDEMY-UC-7462019',
    verifyUrl: 'https://udemy.com/certificate/UC-node-backend',
    skillsCovered: ['Express Middleware', 'REST Architecture', 'Mongoose ODM', 'JWT Security'],
    image: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 4,
    title: 'JavaScript Algorithms and Data Structures',
    issuer: 'freeCodeCamp Certification',
    date: 'May 2023',
    credentialId: 'FCC-JS-992140',
    verifyUrl: 'https://freecodecamp.org/certification/siab-khan/javascript-algorithms',
    skillsCovered: ['ES6+', 'Object-Oriented Programming', 'Functional Programming', 'Big-O Analysis'],
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=800&auto=format&fit=crop',
  },
];

export const TESTIMONIALS_DATA: Testimonial[] = [
  {
    id: 1,
    name: 'Sarah Jenkins',
    role: 'VP of Product',
    company: 'CloudScale Technologies',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
    content: 'Siab is an exceptional engineer. He transformed our complex analytical requirements into a fluid, blisteringly fast dashboard. His dedication to clean code, subtle micro-interactions, and communication made collaborating a breeze.',
    rating: 5,
  },
  {
    id: 2,
    name: 'David Chen',
    role: 'Engineering Lead',
    company: 'Vanguard Interactive',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
    content: 'Working with Siab on our design system rollout was one of the smoothest experiences in my career. His understanding of React architectures, Tailwind, and accessible UI is top-tier. Highly recommended for any serious engineering team!',
    rating: 5,
  },
  {
    id: 3,
    name: 'Elena Rostova',
    role: 'Founder & CEO',
    company: 'Nexus Commerce Group',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    content: 'Siab delivered our full-stack e-commerce project well ahead of our launch schedule. Our bounce rate dropped noticeably and conversion jumped by 28% after the refresh. A true craftsman.',
    rating: 5,
  },
];


